# Generated by Django 2.1.1 on 2019-06-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190624_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
