# Generated by Django 2.1.1 on 2019-06-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190624_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
