# Generated by Django 2.1.1 on 2019-06-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_product_sell_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='size',
        ),
        migrations.RemoveField(
            model_name='video',
            name='size',
        ),
    ]
