# Generated by Django 2.1.1 on 2019-06-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190624_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='size',
        ),
    ]
