# Generated by Django 2.1.1 on 2019-06-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_book_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='quize',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quize',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sound',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/videos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sound',
            name='time_duration',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.TextField(),
        ),
    ]
