# Generated by Django 2.1.1 on 2019-06-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190624_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='uploads/books'),
        ),
        migrations.AlterField(
            model_name='quize',
            name='file',
            field=models.FileField(upload_to='uploads/quizes'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='file',
            field=models.FileField(upload_to='uploads/sounds'),
        ),
    ]
