# Generated by Django 2.1.1 on 2019-06-25 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190625_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='question_count',
            new_name='page_count',
        ),
    ]
