# Generated by Django 2.1.1 on 2019-06-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190619_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
